import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
const base = process.env.TEST_URL;
if (!base || !/^http:\/\/(localhost|127\.0\.0\.1):[0-9]+$/.test(base)) throw new Error('TEST_URL must point at the local scratch Worker');
async function call(path, body, token, origin=base) {
  const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Origin:origin,...(token?{Authorization:'Bearer '+token}:{})},body:body?JSON.stringify(body):undefined});
  return {status:r.status,data:await r.json()};
}
const testName='API '+randomUUID().slice(0,8);
const player=await call('/api/player',{name:testName});
assert.equal(player.status,201);
const token=player.data.token;
const run={id:randomUUID(),mode:'strict',version:'v48-2',stage:'all',weapon:'pistol',score:9876,accuracy:98,wpm:65};
assert.equal((await call('/api/scores',run)).status,401);
assert.equal((await call('/api/scores',run,token,'https://foreign.example')).status,403);
assert.equal((await call('/api/scores',{...run,mode:'normal'},token)).status,400);
const saved=await call('/api/scores',run,token);
assert.equal(saved.status,200); assert.equal(saved.data.best,9876);
assert.equal((await call('/api/scores',run,token)).status,200);
assert.equal((await call('/api/scores',{...run,score:9999},token)).status,409);
await call('/api/scores',{...run,id:randomUUID(),score:123},token);
const board=await call('/api/leaderboard?mode=strict',null,token);
assert.equal(board.data.best,9876);
assert.equal(board.data.board.filter(r=>r.name===testName).length,1);
assert.equal((await call('/api/leaderboard?mode=original',null,token)).data.best,0);
const other=await call('/api/player',{name:'Other Tester'});
assert.equal((await call('/api/leaderboard?mode=strict',null,other.data.token)).data.best,0);
assert.equal((await call('/api/scores',run,other.data.token)).status,409);
for(let i=0;i<3;i++) assert.equal((await call('/api/scores',{...run,id:randomUUID(),score:200+i},token)).status,200);
assert.equal((await call('/api/scores',{...run,id:randomUUID()},token)).status,429);
assert.equal((await call('/api/scores',run,token)).status,200);
const raceRun={...run,id:randomUUID()};
const race=await Promise.all([call('/api/scores',raceRun,other.data.token),call('/api/scores',{...raceRun,score:9998},other.data.token)]);
assert.deepEqual(race.map(r=>r.status).sort(),[200,409]);
// per-stage boards: a third player saves to two stages; the boards stay separate and show the weapon
const stager=(await call('/api/player',{name:'Stage '+randomUUID().slice(0,6)})).data.token;
assert.equal((await call('/api/scores',{...run,id:randomUUID(),stage:'nowhere'},stager)).status,400);
assert.equal((await call('/api/scores',{...run,id:randomUUID(),weapon:'bazooka'},stager)).status,400);
const g=await call('/api/scores',{...run,id:randomUUID(),stage:'gate',weapon:'ray',score:4444},stager);
assert.equal(g.status,200); assert.equal(g.data.stage,'gate'); assert.equal(g.data.best,4444);
assert.equal((await call('/api/scores',{...run,id:randomUUID(),stage:'crypt',weapon:'xbow',score:3333},stager)).data.best,3333);
const gb=await call('/api/leaderboard?mode=strict&stage=gate',null,stager);
assert.equal(gb.data.best,4444); assert.equal(gb.data.stage,'gate'); assert.ok(gb.data.board.some(r=>r.score===4444&&r.weapon==='ray'));
assert.ok(!gb.data.board.some(r=>r.score===9876));
assert.equal((await call('/api/leaderboard?mode=strict',null,stager)).data.best,0);
assert.equal((await call('/api/leaderboard?mode=strict&stage=nowhere')).status,400);
console.log('Live local API: per-stage boards and weapons passed');
console.log('Live local API: identity, validation, origin, duplicates, best, separate modes, ownership and rate limit passed');
